# Generated by Django 3.2.4 on 2021-06-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_usernew'),
    ]

    operations = [
        migrations.CreateModel(
            name='gmailNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=70)),
                ('subject', models.CharField(max_length=70)),
                ('message', models.CharField(max_length=70)),
            ],
        ),
    ]
