# Generated by Django 3.2.4 on 2021-07-01 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_gmailnew'),
    ]

    operations = [
        migrations.CreateModel(
            name='twitterNew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertweet', models.CharField(max_length=100)),
            ],
        ),
    ]
